insert into t_book(title,author,isbn,release_date,gener,page_number,series) values ('Harry Potter and the Sorcerers Stone','J.K.Rowling','9781781103821 ','June 26th 1997','Fantasy',309,'Harry Potter #1')
insert into t_book(title,author,isbn,release_date,gener,page_number,series) values ('Game of Thrones','George R.R. Martin','9780553588484','August 6th 1996','Fantasy',835,'A Song of Ice and Fire #1')
insert into t_book(title,author,isbn,release_date,gener,page_number,series) values ('Outlander','Diana Gabaldon','9780440242949','June 1st 1991','Historical Fiction',850,'Outlander #1')
insert into t_book(title,author,isbn,release_date,gener,page_number,series) values ('Dragonfly in Amber','Diana Gabaldon','9780440242949','July 1st 1992','Historical Fiction',947,'Outlander #2')
insert into t_people(firstname,lastname,username,email,age,password) values ('Andrea','Munteanu','andimunte','andimunte@email.com',20,'pasd')
insert into t_people(firstname,lastname,username,email,age,password) values ('Iulia','Popa','popai','popai@email.com',20,'pasd')
insert into t_people(firstname,lastname,username,email,age,password) values ('Sorina','Radu','radus','radus@email.com',20,'pasd')
insert into t_people(firstname,lastname,username,email,age,password) values ('Valentin','Matei','valimat','valimat@email.com',20,'pasd')
insert into t_people(firstname,lastname,username,email,age,password) values ('Robert','Dumitru','robidumi','robidumi@email.com',20,'pasd')
insert into t_read(id_book, id_people, start_date, end_date) values (1,1,'13.05.2021','18.05.2021')
insert into t_read(id_book, id_people, start_date, end_date) values (1,2,'01.10.2021','29.10.2021')
insert into t_read(id_book, id_people, start_date, end_date) values (2,2,'03.02.2022','15.02.2022')
insert into t_read(id_book, id_people, start_date, end_date) values (2,3,'15.12.2012','15.02.2022')
insert into t_read(id_book, id_people, start_date, end_date) values (2,4,'03.01.2022','15.06.2022')

